name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  REPO: ${{ secrets.REPO }}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          dockerfile: ./Dockerfile
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest

  deploy:
    needs: build
    environment: production
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URI: ${{ secrets.REDIS_URI }}
      NODEMAILER_PW: ${{secrets.NODEMAILER_PW}}
      NODEMAILER_EMAIL: ${{secrets.NODEMAILER_EMAIL}}
      AUTH_URL: ${{secrets.AUTH_URL}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      RAZORPAY_ID: ${{ secrets.RAZORPAY_ID }}
      RAZORPAY_KEY: ${{ secrets.RAZORPAY_KEY }}
      SHIPROCKET_EMAIL: ${{ secrets.SHIPROCKET_EMAIL }}
      SHIPROCKET_PASSWORD: ${{ secrets.SHIPROCKET_PASSWORD }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} 'docker stop ${{ env.REPO }} || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} 'docker rm ${{ env.REPO }} || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} 'docker rmi -f $(docker images ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO }} -aq) || true'

      - name: Pull Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} 'docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest'

      - name: Create .env file
        run:  |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "REDIS_URI=${{ secrets.REDIS_URI }}" >> .env
          echo "NODEMAILER_PW=${{ secrets.NODEMAILER_PW }}" >> .env
          echo "NODEMAILER_EMAIL=${{ secrets.NODEMAILER_EMAIL }}" >> .env
          echo "AUTH_URL=${{ secrets.AUTH_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "RAZORPAY_ID=${{ secrets.RAZORPAY_ID }}" >> .env
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> .env
          echo "SHIPROCKET_EMAIL=${{ secrets.SHIPROCKET_EMAIL }}" >> .env
          echo "SHIPROCKET_PASSWORD=${{ secrets.SHIPROCKET_PASSWORD }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env

          scp -o StrictHostKeyChecking=no -i key.pem .env ${{ env.AWS_HOST }}:~/

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} 'docker run -d -p 8000:8000 --env-file .env --name ${{ env.REPO }} ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest'
      - name: Copy nginx.conf to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem .nginx/nginx.conf ${{ env.AWS_HOST }}:~/.nginx/
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ env.AWS_HOST }} '
          sudo mv ~/.nginx/nginx.conf /etc/nginx/nginx.conf
          sudo systemctl restart nginx
          '

